### ISSUE TITLE
-f custom path argument on Windows dont work, fail on profile write

### ISSUE THREAD

**Issue by cornebester** [onelogin/onelogin-aws-cli-assume-role#10]
Tested both Powershell and CMD shells with and without a period in foldername 

```
....
AWS Region (us-west-2): us-east-1
Exception in thread "main" com.amazonaws.SdkClientException: Unable to restore the original credentials file. File content stashed in C:\scratch\aws.bak.a742c34a-f9b6-45c3-97bd-ef39dabd60a0
        at com.amazonaws.auth.profile.ProfilesConfigFileWriter.modifyProfiles(ProfilesConfigFileWriter.java:232)
        at com.amazonaws.auth.profile.ProfilesConfigFileWriter.modifyOneProfile(ProfilesConfigFileWriter.java:129)
        at com.onelogin.aws.assume.role.cli.OneloginAWSCLI.main(OneloginAWSCLI.java:331)
```

**Comment by pitbulk** [comment]
It seems an issue on the [modifyProfiles](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/profile/ProfilesConfigFileWriter.java#L231) method of the ProfilesConfigFileWriter.  Is maybe a permission issue?

**Comment by cornebester** [comment]
Don't think so as it creates the .aws.bak. file and remove current .aws. Documentation is a bit vague, do I use path only or need to include credential file? e.g. -f "c:\scratch\.aws"


-f,--file <arg>        Set a custom path to save the AWS credentials. (if
                        not used, default AWS path is used)

**Comment by cornebester** [comment]
User error, I omitted filer name. By specifying -f  "custom path\credentials" this works.
