### ISSUE TITLE
Password command-line option?

### ISSUE THREAD

**Issue by pzelnip** [onelogin/onelogin-aws-cli-assume-role#14]
It'd be nice to have a ```--password``` option on the command line like the [Python client](https://github.com/onelogin/onelogin-python-aws-assume-role#step-1-provide-onelogin-data) has.  One can echo it, ie:

```
echo "mypassword" | java -jar onelogin-aws-cli.jar ...all the other options...
```
But if one has a MFA device like a Yubikey set up, the echo messes with that:
```
$ echo "mypassword" | java -jar onelogin-aws-cli.jar --username myusername --appid 123456 --subdomain subdomain --profile default --region ca-central-1

OneLogin AWS Assume Role Tool

18:53:25.338 [main] DEBUG com.onelogin.sdk.util.Settings - properties file onelogin.sdk.properties loaded succesfully
OneLogin Username: myusername
OneLogin Password: AWS App ID: 123456
Onelogin Instance Sub Domain: subdomain

MFA Required
Authenticate using one of these devices:
-----------------------------------------------------------------------
Enter the OTP Token for Yubico YubiKey: Exception in thread "main" java.util.NoSuchElementException
	at java.util.Scanner.throwFor(Scanner.java:862)
	at java.util.Scanner.next(Scanner.java:1371)
	at com.onelogin.aws.assume.role.cli.OneloginAWSCLI.getSamlResponse(OneloginAWSCLI.java:390)
	at com.onelogin.aws.assume.role.cli.OneloginAWSCLI.main(OneloginAWSCLI.java:206)
```

**Comment by pitbulk** [comment]
Noted

**Comment by Subterrane** [comment]
Closing as already implemented.

The `--password` flag was added to this CLI at some point after this issue was filed in 2018 (apologies for the silence on the thread). It's listed in `--help` and documented in the [README](https://github.com/onelogin/onelogin-aws-cli-assume-role#cli) — including a security caveat about process-list visibility and a recommended composition with a password manager:

```
--password $(security find-generic-password -a $USER -s onelogin -w)
```

For the specific echo-pipe-vs-MFA-Yubikey interaction shown in the original report, PR #54 just added a complementary `--otp-token` flag (#42). Passing both `--password` and `--otp-token` as arguments lets you avoid piping anything to stdin, which is the underlying cause of the `NoSuchElementException` reported here.

Please reopen if there's a specific behavior gap not covered by these two flags.
