### ISSUE TITLE
NumberFormatException thrown when running loop

### ISSUE THREAD

**Issue by braun1928** [onelogin/onelogin-aws-cli-assume-role#17]
Environment: configured the onelogin.sdk.properties normally, passing information in arguments (except password), using --profile and --loop. My user has MFA app configured, which works normally for the first run. The .aws/credentials is updated, works correctly.
When the session ends, hence, running the authentication for the second time, I get an NFE:

`Temporary AWS Credentials Granted via OneLogin

Updated AWS profile 'saml' located at /Users/braun/.aws/credentials
This process will regenerate credentials 9 more times.

Press Ctrl + C to exit
Exception in thread "main" java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:552)
	at java.lang.Long.parseLong(Long.java:631)
	at com.onelogin.aws.assume.role.cli.OneloginAWSCLI.getSamlResponse(OneloginAWSCLI.java:458)
	at com.onelogin.aws.assume.role.cli.OneloginAWSCLI.main(OneloginAWSCLI.java:256)`

I didn't find anything on past issues related to this. Since this client doesn't have logging for debugging, I'm gonna start to modify the code to print everything, to see if I can have more info on what happened.

Mac OS X 10.14.2, Java 1.8.0_201

**Comment by braun1928** [comment]
After some thought, issue is that the deviceId is **not** in the mfaVerifyInfo map. I've added that info, the exception is not thrown anymore, but it gets stuck in OTP verification, always returning that the token is invalid -- except in the first run, where everything works.

**Comment by WtfJoke** [comment]
Experience the same issue:
```bash
Temporary AWS Credentials Granted via OneLogin

Updated AWS profile 'default' located at C:\Users\Manuel\.aws\credentials
This process will regenerate credentials 1 more times.

Press Ctrl + C to exit
Exception in thread "main" java.lang.NumberFormatException: null
        at java.lang.Long.parseLong(Long.java:552)
        at java.lang.Long.parseLong(Long.java:631)
        at com.onelogin.aws.assume.role.cli.OneloginAWSCLI.getSamlResponse(OneloginAWSCLI.java:458)
        at com.onelogin.aws.assume.role.cli.OneloginAWSCLI.main(OneloginAWSCLI.java:256)
```

Could it be that this is a windows issue? 
Any plans to fix this?

**Comment by pitbulk** [comment]
I see 2 issues here:

1. Catch null or empty deviceId. I should replace at line [510](https://github.com/onelogin/onelogin-aws-cli-assume-role/blob/master/onelogin-aws-assume-role-cli/src/main/java/com/onelogin/aws/assume/role/cli/OneloginAWSCLI.java#L510)
```
deviceIdStr = mfaVerifyInfo.get("deviceId");
					if (!checkDeviceExists(devices, Long.parseLong(deviceIdStr))) {
						System.out.println();
						System.out.println("The device selected with ID " + deviceIdStr + " is not available anymore");
						System.out.println("Those are the devices available now:");
						mfaVerifyInfo = null;
					}
```
by
```
deviceIdStr = mfaVerifyInfo.get("deviceId");
                                         if (deviceIdStr == null || deviceIdStr.isEmpty()) {
						System.out.println("No device info found");
						mfaVerifyInfo = null;
				        } else if (!checkDeviceExists(devices, Long.parseLong(deviceIdStr))) {
						System.out.println();
						System.out.println("The device selected with ID " + deviceIdStr + " is not available anymore");
						System.out.println("Those are the devices available now:");
						mfaVerifyInfo = null;
					}
```

2. I may store the deviceId info into mfaVerifyInfo. At line [541](https://github.com/onelogin/onelogin-aws-cli-assume-role/blob/master/onelogin-aws-assume-role-cli/src/main/java/com/onelogin/aws/assume/role/cli/OneloginAWSCLI.java#L541) replace:

```
    mfaVerifyInfo = new HashMap<String, String>();
    mfaVerifyInfo.put("otpToken", otpToken);
    mfaVerifyInfo.put("stateToken", stateToken);
```
by
```
    mfaVerifyInfo = new HashMap<String, String>();
    mfaVerifyInfo.put("otpToken", otpToken);
    mfaVerifyInfo.put("stateToken", stateToken);
    mfaVerifyInfo.put("deviceId", deviceIdStr);

```

**Comment by vgropp** [comment]
@pitbulk i tried your suggestions (https://github.com/onelogin/onelogin-aws-cli-assume-role/issues/17#issuecomment-694420102) but that leads to either
```
Exception in thread "main" OAuthProblemException{error='Unauthorized', description='Invalid Token', uri='null', state='401', scope='null', redirectUri='null', responseStatus=401, parameters={}}
        at org.apache.oltu.oauth2.common.exception.OAuthProblemException.error(OAuthProblemException.java:59)
        at org.apache.oltu.oauth2.client.validator.OAuthClientValidator.validateErrorResponse(OAuthClientValidator.java:63)
        at org.apache.oltu.oauth2.client.validator.OAuthClientValidator.validate(OAuthClientValidator.java:48)
        at org.apache.oltu.oauth2.client.response.OAuthClientResponse.validate(OAuthClientResponse.java:127)
        at com.onelogin.sdk.conn.OneloginOAuthJSONAccessTokenResponse.init(OneloginOAuthJSONAccessTokenResponse.java:27)
        at org.apache.oltu.oauth2.client.response.OAuthClientResponse.init(OAuthClientResponse.java:101)
        at org.apache.oltu.oauth2.client.response.OAuthAccessTokenResponse.init(OAuthAccessTokenResponse.java:60)
        at org.apache.oltu.oauth2.client.response.OAuthClientResponse.init(OAuthClientResponse.java:120)
        at org.apache.oltu.oauth2.client.response.OAuthClientResponseFactory.createCustomResponse(OAuthClientResponseFactory.java:82)
        at com.onelogin.sdk.conn.OneloginURLConnectionClient.execute(OneloginURLConnectionClient.java:75)
        at com.onelogin.sdk.conn.Client.updateTokens(Client.java:3799)
        at com.onelogin.sdk.conn.Client.refreshToken(Client.java:224)
        at com.onelogin.sdk.conn.Client.prepareToken(Client.java:3705)
        at com.onelogin.sdk.conn.Client.getSAMLAssertion(Client.java:2213)
        at com.onelogin.aws.assume.role.cli.OneloginAWSCLI.getSamlResponse(OneloginAWSCLI.java:489)
        at com.onelogin.aws.assume.role.cli.OneloginAWSCLI.main(OneloginAWSCLI.java:294)
```

or it looks refreshed but im not actually logged in. So there seems to be another issue missing. I did not yet have time to debug  it

**Comment by pitbulk** [comment]
> OAuthProblemException{error='Unauthorized', description='Invalid Token'

This means that the client_id / client_secret were wrong so not able to generate right access_token.
