### ISSUE TITLE
Warning about prepended `profile`, but latest AWS CLI doesn't support

### ISSUE THREAD

**Issue by vdczzz** [onelogin/onelogin-aws-cli-assume-role#18]
After downloading the latest version of the jar, the latest `awscli`, a fresh `~/.aws` directory, running `aws configure --profile default` while only setting the region, and running the java command...

```
$ aws --version
aws-cli/1.16.30 Python/3.7.0 Darwin/18.0.0 botocore/1.12.20
$ rm ~/.aws/config
$ cat ~/.aws/config
cat: /Users/vdc/.aws/config: No such file or directory
$ aws configure --profile default
AWS Access Key ID [None]:
AWS Secret Access Key [None]:
Default region name [None]: us-west-2
Default output format [None]:
$ cat ~/.aws/config
[profile default]
region = us-west-2
$ java -jar onelogin-aws-cli.jar -r us-west-2 -d "redacted" -a "redacted" -u "${USER}" -p default
```

I get this notice at the bottom of the jar output:

```
AWS Region: us-west-2Feb 27, 2019 12:14:48 PM com.amazonaws.profile.path.cred.CredentialsLegacyConfigLocationProvider getLocation
WARNING: Found the legacy config profiles file at [/Users/vdc/.aws/config]. Please move it to the latest default location [~/.aws/credentials].
Feb 27, 2019 12:14:48 PM com.amazonaws.auth.profile.internal.BasicProfileConfigLoader loadProfiles
WARNING: The legacy profile format requires the 'profile ' prefix before the profile name. The latest code does not require such prefix, and will consider it as part of the profile name. Please remove the prefix if you are seeing this warning.

-----------------------------------------------------------------------
Success!

Temporary AWS Credentials Granted via OneLogin

Updated AWS profile 'default' located at /Users/vdc/.aws/config
```

When I don't specify a profile in `aws configure`, I still get an warning that something is legacy:

```
$ aws configure
AWS Access Key ID [None]:
AWS Secret Access Key [None]:
Default region name [None]: us-west-2
Default output format [None]:
$ cat ~/.aws/config
[default]
region = us-west-2
$ java -jar aws/onelogin-aws-cli.jar -r us-west-2 -d "redacted" -a "redacted" -u "${USER}" -p default
Unable to find a $JAVA_HOME at "/usr", continuing with system-provided Java...

OneLogin AWS Assume Role Tool

OneLogin Username: vdc
OneLogin Password:
AWS App ID: redacted
Onelogin Instance Sub Domain: redacted

Available AWS Roles
-----------------------------------------------------------------------
 0 | OneLogin-SAML-ENG-ROLE (Account redacted)
 1 | OneLogin-SAML-Role (Account redacted)
-----------------------------------------------------------------------
Select the desired Role [0-1]: 0
AWS Region: us-west-2Feb 27, 2019 1:37:03 PM com.amazonaws.profile.path.cred.CredentialsLegacyConfigLocationProvider getLocation
WARNING: Found the legacy config profiles file at [/Users/vdc/.aws/config]. Please move it to the latest default location [~/.aws/credentials].

-----------------------------------------------------------------------
Success!

Temporary AWS Credentials Granted via OneLogin

Updated AWS profile 'default' located at /Users/vdc/.aws/config
```

And here's what happens if I never run `aws configure` and then run the tool:

```
AWS Region: us-west-2Exception in thread "main" java.lang.NullPointerException
	at com.amazonaws.auth.profile.ProfilesConfigFileWriter.modifyProfiles(ProfilesConfigFileWriter.java:159)
	at com.amazonaws.auth.profile.ProfilesConfigFileWriter.modifyOneProfile(ProfilesConfigFileWriter.java:129)
	at com.onelogin.aws.assume.role.cli.OneloginAWSCLI.main(OneloginAWSCLI.java:401)
```

I realize I'm just getting warnings (aside from the last example) but I don't think my usage is legacy if I'm running the `aws configure` tool. Although, it would be great to accommodate the last pattern since that would help users get connected without having to run another command. Right now I have a wrapper script that handles both for users, but I'd really like to avoid the warnings.

**Comment by ldormoy** [comment]
I have a similar issue:
Using the `-p`  option creates an aws config file with the corresponding profile, but the `profile` keyword is missing in the config. 

I think there is a confusion between credentials profile and config profile on your end.

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

> The credentials file uses a different naming format than the CLI config file for named profiles. Include the prefix word "profile" only when configuring a named profile in the config file. Do not use the word profile when creating an entry in the credentials file. 

Can you please add the `profile` prefix when generating a config with profiles?

**Comment by Subterrane** [comment]
Triage note (2026-05-22):

This issue actually contains three distinct symptoms that need separate consideration:

1. **`CredentialsLegacyConfigLocationProvider` warning** — "Found the legacy config profiles file at [~/.aws/config]. Please move it to the latest default location [~/.aws/credentials]." This is emitted by the AWS SDK itself when it sees the CLI tool writing region into `~/.aws/config`. Recent PR #53 only stripped a `profile ` prefix from CLI input — it does not touch this code path.

2. **`'profile ' prefix is legacy` warning** — partially related to PR #53. PR #53 helps users who passed `--profile "profile default"`, but in the original report the user passed `-p default` (no prefix), so PR #53 won't change this case either. The warning comes from how the SDK reads the `[profile default]` section written by `aws configure`.

3. **`NullPointerException at OneloginAWSCLI.java:401`** when no `aws configure` had ever been run. The current equivalent call site is around lines 507/514 (`ProfilesConfigFileWriter.modifyOneProfile`). This is a real bug independent of the warnings.

**Keeping open.** Would benefit from someone reproducing against current master (post-PR-53) with both an existing `~/.aws/config` and with no `~/.aws/*` files to confirm which of the three are still live.
