### ISSUE TITLE
v1.1.3 not working: this.settings is null

### ISSUE THREAD

**Issue by dududko** [onelogin/onelogin-aws-cli-assume-role#41]
Trying to use the latest release of onelogin-aws-cli v1.1.3 and have the following error.
```
MFA Required
Authenticate using one of these devices:
-----------------------------------------------------------------------
Enter the OTP Token for Yubico YubiKey: ###########
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.onelogin.saml2.settings.Saml2Settings.isTrimAttributeValues()" because "this.settings" is null
	at com.onelogin.saml2.authn.SamlResponse.getAttributes(SamlResponse.java:612)
	at com.onelogin.aws.assume.role.cli.OneloginAWSCLI.main(OneloginAWSCLI.java:303)
```

The previous version v1.1.2 works well on the same application.

**Comment by chaoyangnz** [comment]
same issue
