### ISSUE TITLE
Quickstart Guide is incomplete

### ISSUE THREAD

**Issue by chizou** [onelogin/onelogin-aws-cli-assume-role#7]
The quickstart instructions make it seem like all you need to do is download the jar file and execute it. However, you're quickly met with an error...
```
14:23:59.761 [main] ERROR com.onelogin.sdk.util.Settings - properties file 'onelogin.sdk.properties' not found in the classpath
Exception in thread "main" com.onelogin.sdk.exception.Error: properties file 'onelogin.sdk.properties' not found in the classpath
	at com.onelogin.sdk.util.Settings.loadPropFile(Settings.java:112)
	at com.onelogin.sdk.util.Settings.<init>(Settings.java:38)
	at com.onelogin.sdk.conn.Client.<init>(Client.java:123)
	at com.onelogin.sdk.conn.Client.<init>(Client.java:129)
	at com.onelogin.aws.assume.role.cli.OneloginAWSCLI.main(OneloginAWSCLI.java:125)
```

I have to follow the link to the detailed instructions in order to properly use the quickstart guide. That kind of defeats the purpose of calling it "Quickstart"

**Comment by pitbulk** [comment]
Sorry for the confusion. 

Documentation updated: 87da257f4c9d585de4563f5b1fab05357b1a5920
